
services:
  fitting:
    container_name: fit 
    build:
      context: ./fit 
      dockerfile: Dockerfile.fit 
    volume:
      - ./inputs:/usr/src/app/inputs
      - ./outputs:/usr/src/app/outputs
  serving:
    container_name: serve 
    build: 
      context: ./serve 
      dockerfile: Dockerfile.serve
    volume:
      - ./outputs:/usr/src/app/outputs
    ports:
      - 6000:80
  webserver:
    container_name: web
    build:
      context: ./web 
      dockerfile: Dockerfile.web
    ports:
      - 7000:8000

    

